'use client';
import {useState,useCallback,useEffect} from 'react';
import SignIn from '../components/SignIn';
import {api} from '../../lib/api.mjs';
import {useSession} from '../../lib/useSession.mjs';
import AccountBar from '../components/AccountBar';
const words={deposit:'Seña',provider_fee:'Comisión',fee_subsidy:'Comisión subsidiada',refund:'Devolución',compensation:'Compensación',payout:'Transferencia',review:'En revisión',confirmed:'Confirmado',void:'Anulado',pending_payment:'Pago pendiente',reserved:'Apartado',delivered:'Entregado',expired:'Vencido',payment_failed:'Pago fallido',cancelled:'Cancelado',payment_review:'Pago en revisión'};
export default function Operations(){
 const [session,onSession]=useSession();
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const refresh=useCallback(async()=>{if(!session)return;try{setData({...await api('operations',{token:session.access_token}),_viewer:session.user.id});setError('')}catch(e){setError(e.message)}},[session]);
 useEffect(()=>{setData(null);refresh()},[refresh]);
 async function action(body){setBusy(true);try{await api('operations',{method:'POST',token:session.access_token,body});await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <main className="dashboard"><span className="eyebrow">PILOTO · EL SALVADOR</span><h1>Operaciones</h1>{!session?<SignIn operations onSession={onSession}/>:<><AccountBar/> <button className="secondary" onClick={refresh}>Actualizar</button>{data&&data._viewer===session.user.id&&<><div className="metrics">{[['Comerciantes activos',data.metrics.activeMerchants],['Publicaciones',data.metrics.listings],['Pagos confirmados',data.metrics.paid],['Entregas',data.metrics.delivered],['No-show',data.metrics.noShows],['Pagos en revisión',data.metrics.reviews],['Mensajes en revisión',data.metrics.messageReview+data.metrics.notificationReview]].map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div><h2>Comerciantes</h2><div className="table-wrap"><table><thead><tr><th>Comerciante</th><th>Canal</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{data.merchants.map(m=><tr key={m.id}><td>{m.display_name??'Sin nombre'}</td><td>{m.chat_id}</td><td>{m.enabled?'Habilitado':'Pendiente'}</td><td>{!m.enabled&&<form onSubmit={e=>{e.preventDefault();action({action:'enable',merchantId:m.id,name:new FormData(e.target).get('name')})}}><input name="name" aria-label="Nombre del comercio" required minLength={2} maxLength={80}/><button disabled={busy}>Habilitar</button></form>}</td></tr>)}</tbody></table></div><h2>Conciliación</h2><p>Los montos registrados no implican una transferencia realizada.</p><div className="table-wrap"><table><thead><tr><th>Comerciante</th><th>Concepto</th><th>Estado</th><th>Monto</th></tr></thead><tbody>{data.settlement.map((x,i)=><tr key={i}><td>{data.merchants.find(m=>m.id===x.merchant_id)?.display_name??x.merchant_id}</td><td>{words[x.kind]??x.kind}</td><td>{words[x.status]??x.status}</td><td>${(x.amount_cents/100).toFixed(2)}</td></tr>)}</tbody></table></div><h2>Pedidos recientes</h2><div className="table-wrap"><table><thead><tr><th>Pedido</th><th>Estado</th><th>Seña</th><th>Registrar comisión real</th></tr></thead><tbody>{data.orders.map(o=><tr key={o.id}><td>{o.id.slice(0,8)}</td><td>{words[o.status]??o.status}</td><td>${(o.deposit_cents/100).toFixed(2)}</td><td><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.target);action({action:'fee',orderId:o.id,feeCents:Number(f.get('fee')),reference:f.get('ref')})}}><input name="fee" type="number" min={0} max={o.deposit_cents} step={1} required aria-label="Comisión en centavos" placeholder="Centavos"/><input name="ref" required maxLength={128} aria-label="Referencia del reporte" placeholder="Referencia"/><button disabled={busy}>Registrar</button></form></td></tr>)}</tbody></table></div></>}</>}{error&&<p role="alert" className="error">{error}</p>}</main>;
}
