'use client';
import {use,useState,useCallback,useEffect} from 'react';
import SignIn from '../../components/SignIn';
import {api} from '../../../lib/api.mjs';
import {useSession} from '../../../lib/useSession.mjs';
import AccountBar from '../../components/AccountBar';
const labels={pending_payment:'Tu pago todavía no está confirmado',reserved:'Tu artículo está apartado',delivered:'Entrega confirmada',expired:'El apartado venció',payment_failed:'El pago no se completó',payment_review:'Estamos revisando tu pago',cancelled:'Pedido cancelado'};
export default function Order({params}){
 const {id}=use(params); const [session,onSession]=useSession(); const [order,setOrder]=useState(null),[error,setError]=useState('');
 const refresh=useCallback(async()=>{if(!session)return;try{setOrder({...await api(`orders?id=${encodeURIComponent(id)}`,{token:session.access_token}),_viewer:session.user.id});setError('')}catch(e){setError(e.message)}},[session,id]);
 useEffect(()=>{setOrder(null);refresh();const timer=setInterval(refresh,15000);return()=>clearInterval(timer)},[refresh]);
 return <main className="narrow"><span className="eyebrow">TU APARTADO</span>{!session?<SignIn onSession={onSession}/>:!order||order._viewer!==session.user.id?<><h1>Consultando tu pedido…</h1><button onClick={refresh}>Volver a consultar</button></>:<><AccountBar/><h1>{labels[order.status]??'Consultá tu pedido'}</h1>{order.pickupCode&&<div className="pickup-code"><span>Mostralo al recibir el artículo</span><strong>{order.pickupCode}</strong></div>}<div className="receipt"><div><span>Precio total</span><b>${(order.price/100).toFixed(2)}</b></div><div><span>{order.status==='reserved'?'Saldo al retirar':'Seña del pedido'}</span><b>${((order.status==='reserved'?order.price-order.deposit:order.deposit)/100).toFixed(2)}</b></div></div><h2>Punto de retiro</h2><p>{order.pickupPoint}</p>{order.deadline&&<p>Retiro hasta: {new Date(order.deadline).toLocaleString('es-SV',{timeZone:'America/El_Salvador'})}</p>}{order.checkoutUrl?<a className="button" href={order.checkoutUrl}>Ir al pago seguro en Wompi ↗</a>:order.status==='pending_payment'&&<p className="notice">Estamos verificando el enlace de pago. No hagás otro pago por este pedido.</p>}{['expired','payment_review','cancelled'].includes(order.status)&&<p>Si realizaste un pago, consultá con operaciones para revisar su estado. Esta pantalla no confirma un reembolso.</p>}<button className="secondary" onClick={refresh}>Actualizar estado</button>{order.canRetry&&order.listingSlug&&<button onClick={()=>{sessionStorage.removeItem(`apartaya:checkout:${session.user.id}:${order.listingSlug}:${order.paymentMethod}`);window.location.assign(`/${order.listingSlug}`)}}>Volver al artículo para intentar de nuevo</button>}{order.paymentReview&&<p className="error">Hay un pago en revisión. No hagás otro pago hasta resolverlo con operaciones.</p>}</>}{error&&<p className="error" role="alert">{error}</p>}</main>;
}
